export const parkingSpotsMap3 = [
    { id: 1, row: 1, col: 1, state: '', type: 'empty-space' },
    { id: 2, row: 1, col: 2, state: 'available', type: 'parking-slot' },
    { id: 3, row: 1, col: 3, state: 'available', type: 'parking-slot' },
    { id: 4, row: 1, col: 4, state: 'available', type: 'parking-slot' },
    { id: 5, row: 1, col: 5, state: 'available', type: 'parking-slot' },
    { id: 6, row: 1, col: 6, state: 'available', type: 'parking-slot' },
    { id: 7, row: 1, col: 7, state: 'available', type: 'parking-slot' },
    { id: 8, row: 1, col: 8, state: 'available', type: 'parking-slot' },
    { id: 9, row: 1, col: 9, state: 'available', type: 'parking-slot' },
    { id: 10, row: 1, col: 10, state: 'available', type: 'parking-slot' },
    { id: 11, row: 1, col: 11, state: 'available', type: 'parking-slot' },
    { id: 12, row: 1, col: 12, state: '', type: 'empty-space' },

    { id: 20, row: 2, col: 1, state: 'available', type: 'parking-slot' },
    { id: 21, row: 2, col: 2, state: '', type: 'drive-lane' },
    { id: 22, row: 2, col: 3, state: '', type: 'drive-lane' },
    { id: 23, row: 2, col: 4, state: '', type: 'drive-lane' },
    { id: 24, row: 2, col: 5, state: '', type: 'drive-lane' },
    { id: 25, row: 2, col: 6, state: '', type: 'drive-lane' },
    { id: 26, row: 2, col: 7, state: '', type: 'drive-lane' },
    { id: 27, row: 2, col: 8, state: '', type: 'drive-lane' },
    { id: 28, row: 2, col: 9, state: '', type: 'drive-lane' },
    { id: 29, row: 2, col: 10, state: '', type: 'drive-lane' },
    { id: 30, row: 2, col: 11, state: '', type: 'drive-lane' },
    { id: 31, row: 2, col: 12, state: 'available', type: 'parking-slot' },

    { id: 32, row: 3, col: 1, state: 'available', type: 'parking-slot' },
    { id: 33, row: 3, col: 2, state: '', type: 'drive-lane' },
    { id: 34, row: 3, col: 3, state: 'available', type: 'disabled' },
    { id: 35, row: 3, col: 4, state: 'available', type: 'parking-slot' },
    { id: 36, row: 3, col: 5, state: 'available', type: 'parking-slot' },
    { id: 37, row: 3, col: 6, state: 'available', type: 'parking-slot' },
    { id: 38, row: 3, col: 7, state: 'available', type: 'parking-slot' },
    { id: 39, row: 3, col: 8, state: 'available', type: 'parking-slot' },
    { id: 40, row: 3, col: 9, state: 'available', type: 'parking-slot' },
    { id: 41, row: 3, col: 10, state: 'available', type: 'parking-slot' },
    { id: 42, row: 3, col: 11, state: '', type: 'drive-lane' },
    { id: 43, row: 3, col: 12, state: 'available', type: 'parking-slot' },


    { id: 44, row: 4, col: 1, state: 'available', type: 'parking-slot' },
    { id: 45, row: 4, col: 2, state: '', type: 'drive-lane' },
    { id: 46, row: 4, col: 3, state: 'available', type: 'parking-slot' },
    { id: 47, row: 4, col: 4, state: 'available', type: 'parking-slot' },
    { id: 48, row: 4, col: 5, state: 'available', type: 'parking-slot' },
    { id: 49, row: 4, col: 6, state: 'available', type: 'parking-slot' },
    { id: 50, row: 4, col: 7, state: 'available', type: 'parking-slot' },
    { id: 51, row: 4, col: 8, state: 'available', type: 'parking-slot' },
    { id: 52, row: 4, col: 9, state: 'available', type: 'parking-slot' },
    { id: 53, row: 4, col: 10, state: 'available', type: 'parking-slot' },
    { id: 54, row: 4, col: 11, state: '', type: 'drive-lane' },
    { id: 55, row: 4, col: 12, state: 'available', type: 'parking-slot' },

    { id: 56, row: 5, col: 1, state: '', type: 'entrance-right' },
    { id: 57, row: 5, col: 2, state: '', type: 'drive-lane' },
    { id: 58, row: 5, col: 3, state: '', type: 'drive-lane' },
    { id: 59, row: 5, col: 4, state: '', type: 'drive-lane' },
    { id: 60, row: 5, col: 5, state: '', type: 'drive-lane' },
    { id: 61, row: 5, col: 6, state: '', type: 'drive-lane' },
    { id: 62, row: 5, col: 7, state: '', type: 'drive-lane' },
    { id: 63, row: 5, col: 8, state: '', type: 'drive-lane' },
    { id: 64, row: 5, col: 9, state: '', type: 'drive-lane' },
    { id: 65, row: 5, col: 10, state: '', type: 'drive-lane' },
    { id: 66, row: 5, col: 11, state: '', type: 'drive-lane' },
    { id: 67, row: 5, col: 12, state: '', type: 'exit-left' },

    { id: 68, row: 6, col: 1, state: 'available', type: 'parking-slot' },
    { id: 69, row: 6, col: 2, state: '', type: 'drive-lane' },
    { id: 70, row: 6, col: 3, state: 'available', type: 'parking-slot' },
    { id: 71, row: 6, col: 4, state: 'available', type: 'parking-slot' },
    { id: 72, row: 6, col: 5, state: 'available', type: 'parking-slot' },
    { id: 73, row: 6, col: 6, state: 'available', type: 'parking-slot' },
    { id: 74, row: 6, col: 7, state: 'available', type: 'parking-slot' },
    { id: 75, row: 6, col: 8, state: 'available', type: 'parking-slot' },
    { id: 76, row: 6, col: 9, state: 'available', type: 'parking-slot' },
    { id: 77, row: 6, col: 10, state: 'available', type: 'parking-slot' },
    { id: 78, row: 6, col: 11, state: '', type: 'drive-lane' },
    { id: 79, row: 6, col: 12, state: 'available', type: 'parking-slot' },

    { id: 80, row: 7, col: 1, state: 'available', type: 'disabled' },
    { id: 81, row: 7, col: 2, state: '', type: 'drive-lane' },
    { id: 82, row: 7, col: 3, state: 'available', type: 'disabled' },
    { id: 83, row: 7, col: 4, state: 'available', type: 'parking-slot' },
    { id: 84, row: 7, col: 5, state: 'available', type: 'parking-slot' },
    { id: 85, row: 7, col: 6, state: 'available', type: 'parking-slot' },
    { id: 86, row: 7, col: 7, state: 'available', type: 'parking-slot' },
    { id: 87, row: 7, col: 8, state: 'available', type: 'parking-slot' },
    { id: 88, row: 7, col: 9, state: 'available', type: 'parking-slot' },
    { id: 89, row: 7, col: 10, state: 'available', type: 'parking-slot' },
    { id: 90, row: 7, col: 11, state: '', type: 'drive-lane' },
    { id: 91, row: 7, col: 12, state: 'available', type: 'parking-slot' },

    { id: 92, row: 8, col: 1, state: 'available', type: 'disabled' },
    { id: 93, row: 8, col: 2, state: '', type: 'drive-lane' },
    { id: 94, row: 8, col: 3, state: '', type: 'drive-lane' },
    { id: 95, row: 8, col: 4, state: '', type: 'drive-lane' },
    { id: 96, row: 8, col: 5, state: '', type: 'drive-lane' },
    { id: 97, row: 8, col: 6, state: '', type: 'drive-lane' },
    { id: 98, row: 8, col: 7, state: '', type: 'drive-lane' },
    { id: 99, row: 8, col: 8, state: '', type: 'drive-lane' },
    { id: 100, row: 8, col: 9, state: '', type: 'drive-lane' },
    { id: 101, row: 8, col: 10, state: '', type: 'drive-lane' },
    { id: 102, row: 8, col: 11, state: '', type: 'drive-lane' },
    { id: 103, row: 8, col: 12, state: 'available', type: 'parking-slot' },

    { id: 104, row: 9, col: 1, state: '', type: 'empty-space' },
    { id: 105, row: 9, col: 2, state: 'available', type: 'parking-slot' },
    { id: 106, row: 9, col: 3, state: 'available', type: 'parking-slot' },
    { id: 107, row: 9, col: 4, state: 'available', type: 'parking-slot' },
    { id: 108, row: 9, col: 5, state: 'available', type: 'parking-slot' },
    { id: 109, row: 9, col: 6, state: 'available', type: 'parking-slot' },
    { id: 110, row: 9, col: 7, state: 'available', type: 'parking-slot' },
    { id: 111, row: 9, col: 8, state: 'available', type: 'parking-slot' },
    { id: 112, row: 9, col: 9, state: 'available', type: 'parking-slot' },
    { id: 113, row: 9, col: 10, state: 'available', type: 'parking-slot' },
    { id: 114, row: 9, col: 11, state: 'available', type: 'parking-slot' },
    { id: 115, row: 9, col: 12, state: '', type: 'empty-space' }

];